ShopBridge.UI/Models/ErrorViewModel.cs
using System;

namespace ShopBridge.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ShopBridge.UI/Controllers/APIClientController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using ShopBridge.Application.Logic.Interface;
using ShopBridge.Domain.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShopBridge.UI.Controllers
{
    public class APIClientController : Controller
    {
        private readonly IConfiguration _configure;
        public string apiBaseUrl;
        private readonly IAppClient _appClient;
        private readonly IAppUtility _appUtility;
        public APIClientController(IConfiguration configuration, IAppClient appClient, IAppUtility appUtility)
        {
            _configure = configuration;
            apiBaseUrl = _configure["GlobalizationString:APIUrl"] + "/api";
            _appClient = appClient;
            _appUtility = appUtility;
        }

        [HttpPost]
        public async Task<IActionResult> RquestToAPI([FromBody] RequestData request)
        {
            if (!string.IsNullOrEmpty(request.url))
            {
                var requestUrl = _appClient.CreateRequestUri(apiBaseUrl + request.url);

                var result = await _appClient.PostAsync<ResponseResult<string>>(requestUrl, request.data);

                if (result != null)
                {
                    return Ok(Newtonsoft.Json.JsonConvert.SerializeObject(result));
                }
                else
                {
                    ResponseResult<string> result1 = new ResponseResult<string>();
                    result1.Type = "fail";
                    result1.Message = "Request Failed";

                    return Ok(Newtonsoft.Json.JsonConvert.SerializeObject(result1));
                }
            }
            else
            {
                ResponseResult<string> result = new ResponseResult<string>();
                result.Type = "fail";                
                result.Message = "Invalid request";

                return Ok(Newtonsoft.Json.JsonConvert.SerializeObject(result));
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetRquestToAPI(string url, string queryString, string isGetAll)
        {
            if (!string.IsNullOrEmpty(url))
            {
                var requestUrl = _appClient.CreateRequestUri(apiBaseUrl + url, queryString);
                if (isGetAll == "1")
                {
                    var result = await _appClient.GetAllAsync<string>(requestUrl);
                    //return Ok(Newtonsoft.Json.JsonConvert.SerializeObject(result));

                    if (result != null)
                    {
                        return Ok(Newtonsoft.Json.JsonConvert.SerializeObject(result));
                    }
                    else
                    {
                        ResponseResult<string> result1 = new ResponseResult<string>();
                        result1.Type = "fail";
                        result1.Message = "Request Failed";

                        return Ok(Newtonsoft.Json.JsonConvert.SerializeObject(result1));
                    }
                }
                else
                {
                    var result = await _appClient.GetAsync<string>(requestUrl);
                    //return Ok(Newtonsoft.Json.JsonConvert.SerializeObject(result));

                    if (result != null)
                    {
                        return Ok(Newtonsoft.Json.JsonConvert.SerializeObject(result));
                    }
                    else
                    {
                        ResponseResult<string> result1 = new ResponseResult<string>();
                        result1.Type = "fail";
                        result1.Message = "Request Failed";

                        return Ok(Newtonsoft.Json.JsonConvert.SerializeObject(result1));
                    }
                }
            }
            else
            {
                ResponseResult<string> result = new ResponseResult<string>();
                result.Type = "fail";                
                result.Message = "Invalid request";

                return Ok(Newtonsoft.Json.JsonConvert.SerializeObject(result));
            }
        }
    }
}

ShopBridge.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShopBridge.UI.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ShopBridge.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ShopBridge.UI/Controllers/InventoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using ShopBridge.Application.Logic.Interface;
using ShopBridge.Domain.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShopBridge.UI.Controllers
{
    public class InventoryController : Controller
    {
        private readonly IConfiguration _configure;
        public readonly string apiBaseUrl;
        public readonly string appBaseUrl;
        private readonly IAppClient _appClient;
        private readonly IAppUtility _appUtility;

        public InventoryController(IConfiguration configuration, IAppClient appClient, IAppUtility appUtility)
        {
            _configure = configuration;
            apiBaseUrl = _configure["GlobalizationString:APIUrl"] + "/api";
            appBaseUrl = _configure["GlobalizationString:UIUrl"];
            _appClient = appClient;
            _appUtility = appUtility;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            HttpContext.Response.Cookies.Append("appBaseUrl", appBaseUrl,
            new Microsoft.AspNetCore.Http.CookieOptions()
            {
                Path = "/",
                HttpOnly = false,
                Secure = false
            });
            HttpContext.Response.Cookies.Append("apiBaseUrl", apiBaseUrl,
            new Microsoft.AspNetCore.Http.CookieOptions()
            {
                Path = "/",
                HttpOnly = false,
                Secure = false
            });

            SearchInventoryViewModel searchInventory = new SearchInventoryViewModel();

            var requestUrl = _appClient.CreateRequestUri(apiBaseUrl + "/Inventory/ListOfInventory");

            searchInventory.GetInventories = await _appClient.GetAllAsync<InventoryViewModel>(requestUrl);

            return View(searchInventory);
        }

        [HttpGet]        
        public async Task<IActionResult> Add()
        {
            var requestUrl = _appClient.CreateRequestUri(apiBaseUrl + "/Inventory/FetchInventory", "inventoryId=-1");

            InventoryViewModel inventory = await _appClient.GetAsync<InventoryViewModel>(requestUrl);

            if (inventory == null)
            {
                inventory = new InventoryViewModel();
            }

            return View("Save", inventory);
        }

        [HttpGet]        
        public async Task<IActionResult> Edit(int inventoryId)
        {
            var requestUrl = _appClient.CreateRequestUri(apiBaseUrl + "/Inventory/FetchInventory", "inventoryId=" + inventoryId);
            
            InventoryViewModel inventory = await _appClient.GetAsync<InventoryViewModel>(requestUrl);

            if (inventory == null)
            {
                ViewBag.isAllow = false;
                ModelState.AddModelError("msg", "No record found");
                inventory = new InventoryViewModel();
            }
            else
            {
                ViewBag.isAllow = true;
            }

            return View("Save", inventory);
        }        
    }
}

ShopBridge.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    Test Completed
</div>

ShopBridge.UI/Views/Inventory/Index.cshtml
@model ShopBridge.Domain.ViewModel.SearchInventoryViewModel
@{
}

<div class="container">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Inventory List</h2>
                    <hr class="primary">
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-bordred datatable table-hover display" id="inventory-table" style="width:100%">
                    <thead>
                        <tr>
                            <th>
                                Sr. No.
                            </th>
                            <th>Inventory Name</th>
                            <th>Inventory Description</th>
                            <th>Inventory Price</th>
                            <th>Status</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            if (Model.GetInventories != null)
                            {
                                int count = 1;
                                foreach (var inventory in Model.GetInventories)
                                {
                                    <tr>
                                        <td>@count</td>
                                        <td>@inventory.InventoryName</td>
                                        <td>@inventory.InventoryDescription</td>
                                        <td>@inventory.InventoryPrice</td>
                                        <td>@inventory.AvailableStatus</td>
                                        <td>
                                            <input type="hidden" id="hdnInvId_@count" value="@inventory.InventoryId" />
                                            <span class="btn btn-xs text-success" title="Edit" id="btnEdit_@count"><span class="far fa-edit"></span></span>
                                        </td>
                                        <td>
                                            <span class="btn btn-xs text-danger" title="Delete" id="btnDel_@count"><span class="far fa-trash-alt"></span></span>
                                        </td>
                                    </tr>
                                    count = count + 1;
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="7">No record found</td>
                                </tr>
                            }
                        }
                    </tbody>                    
                </table>
            </div>
        </div>
    </div>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/pagejs/comman.js"></script>
<script src="~/js/sweetalert2.min.js"></script>
<script src="~/pagejs/inventory.js"></script>
<script src="~/js/jquery.dataTables.min.js"></script>
<script src="~/js/dataTables.bootstrap5.min.js"></script>

<style type="text/css">
    tfoot input {
        width: 100%;
        padding: 3px;
        box-sizing: border-box;
    }
</style>

<script type="text/javascript">
    $('.datatable').DataTable({        
        "scrollCollapse": true,
        "paging": true,
        aLengthMenu: [
            [10, 25, 50, 100, 200, -1],
            [10, 25, 50, 100, 200, "All"]
        ],

        iDisplayLength: 25
    });    
</script>

ShopBridge.UI/Views/Inventory/Save.cshtml
@model ShopBridge.Domain.ViewModel.InventoryViewModel
@{

}

<div class="container">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Add Inventory</h2>
                    <hr class="primary">
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Inventory Name</label>
                        <input type="text" class="form-control" value="@Model.InventoryName" id="inventoryName" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Inventory Description</label>
                        <input type="text" class="form-control" value="@Model.InventoryDescription" id="inventoryDesc" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Inventory Price</label>
                        <input type="text" class="form-control numericOnly" value="@Model.InventoryPrice" id="inventoryPrice" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Inventory Availibility : </label>
                        <input type="radio" value="1" name="inventoryAvail" id="invYes" /> <label for="invYes">Yes</label>
                        <input type="radio" value="0" name="inventoryAvail" id="invNo" /> <label for="invNo">No</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @if (Model.InventoryId > 0)
                        {
                            if (ViewBag.isAllow == true)
                            {
                                <input type="button" class="btn btn-success btn-block" value="Update" name="btnUpdate" onclick="updateInventory();" />
                            }
                            else
                            {
                                <span class="text-center alert-info">Wrong details found</span>
                            }
                        }
                        else
                        {
                            <input type="button" class="btn btn-success btn-block" value="Add" name="btnAdd" onclick="addInventory();" />
                        }
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <input type="reset" class="btn btn-danger btn-block" value="Reset" />
                        <input type="hidden" id="hdnInvId" value="@Model.InventoryId" />
                        <input type="hidden" id="hdnAvail" value="@Model.isAvailable" />
                        <span id="spnChk" style="display:none;">
                            @Model.isAvailable
                        </span>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/sweetalert2.min.js"></script>
<script src="~/pagejs/comman.js"></script>
<script src="~/pagejs/inventory.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        var isaval = $("#hdnAvail").val();
        //alert(isaval);
        $("input[name=inventoryAvail][value='" + isaval + "']").prop("checked", true);
    });
</script>

ShopBridge.UI/Views/Inventory/_InventoryList.cshtml
@model List<ShopBridge.Domain.ViewModel.InventoryViewModel>
@{
    Layout = null;
}

<table class="table table-bordred datatable table-hover">
    <thead>
        <tr>
            <th>
                Sr. No.
            </th>
            <th>Inventory Name</th>
            <th>Inventory Description</th>
            <th>Inventory Price</th>
            <th>Status</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @{
            if (Model != null)
            {
                int count = 1;
                foreach (var inventory in Model)
                {
                    <tr>
                        <td>@count</td>
                        <td>@inventory.InventoryName</td>
                        <td>@inventory.InventoryDescription</td>
                        <td>@inventory.InventoryPrice</td>
                        <td>@inventory.AvailableStatus</td>
                        <td>
                            <input type="hidden" id="hdnInvId_@count" value="@inventory.InventoryId" />
                            <span class="btn btn-xs text-success" title="Edit" id="btnEdit_@count"><span class="far fa-edit"></span></span>
                        </td>
                        <td>
                            <span class="btn btn-xs text-danger" title="Delete" id="btnDel_@count"><span class="far fa-trash-alt"></span></span>
                        </td>
                    </tr>
                    count = count + 1;
                }
            }
            else
            {
                <tr>
                    <td colspan="7">No record found</td>
                </tr>
            }
        }
    </tbody>
</table>

ShopBridge.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Inventory Management - Shop Bridge</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/all.css" rel="stylesheet" />
    <link href="~/css/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/css/dataTables.bootstrap5.min.css" rel="stylesheet" />
    
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Shop Bridge - Inventory Management</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark btn-info" asp-area="" asp-controller="Inventory" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark btn-success" asp-area="" asp-controller="Inventory" asp-action="Add">Add new Inventory</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Shop Bridge - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="~/js/jquery.dataTables.min.js"></script>*@
    @*<script src="~/js/dataTables.bootstrap5.min.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>